#!/usr/bin/perl
# convert Pro1sze1ky polish to utf8

use utf8;
use Encode;

while(<>) {
    $_ =~ s/L1/\x{0141}/g;
    $_ =~ s/l1/\x{0142}/g;
    $_ =~ s/A1/\x{0104}/g;
    $_ =~ s/a1/\x{0105}/g;
    $_ =~ s/C1/\x{0106}/g;
    $_ =~ s/c1/\x{0107}/g;
    $_ =~ s/E1/\x{0118}/g;
    $_ =~ s/e1/\x{0119}/g;
    $_ =~ s/N1/\x{0143}/g;
    $_ =~ s/n1/\x{0144}/g;
    $_ =~ s/O1/\x{00D3}/g;
    $_ =~ s/o1/\x{00F3}/g;
    $_ =~ s/S1/\x{015A}/g;
    $_ =~ s/s1/\x{015B}/g;
    $_ =~ s/Z1/\x{0179}/g;
    $_ =~ s/z1/\x{017A}/g;
    $_ =~ s/Z2/\x{017B}/g;
    $_ =~ s/z2/\x{017C}/g;
    print encode('utf-8', $_);
}
